server:
  port: 8889
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://ckapi:ckapipassword@127.0.0.1:8761/eureka/
      
spring:
  application:
    name: run

ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000
  
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread: 
            timeoutInMilliseconds: 5000
            

   
zuul:
  addHostHeader: true
  ribbon:
    eagerLoad: 
      enabled: true
  eureka:
    enabled: false
  ReadTimeout: 60000  
  ConnectTimeout: 60000
  host:
    socketTimeoutMillis: 5000
    connectTimeoutMillis: 5000
  routes:
    product:
      path: /product/**
      stripPrefix: false
      serviceId: product
      
    order:
      path: /order/**
      stripPrefix: false
      serviceId: order   
        
    user:
      path: /user/**
      stripPrefix: false
      serviceId: user
    
    image:
      path: /image/**
      stripPrefix: false
      serviceId: image
      
    sms:
      path: /sms/**
      stripPrefix: false
      serviceId: sms   
     
    coupon:
      path: /coupon/**
      stripPrefix: false
      serviceId: coupon 
      
    stock:
      path: /stock/**
      stripPrefix: false
      serviceId: stock   
      
    accredit:
      path: /accredit/**
      stripPrefix: false
      serviceId: accredit
    
    wechat:
      path: /wechat/**
      stripPrefix: false
      serviceId: wechat
    
      
